module.exports = {
  /* 用户相关 api */
  login: '/api/admin/login', // 登录认证
  userInfo: '/api/admin/user-info', // 用户信息
  editPassword: '/api/admin/edit-password', // 请求修改密码
  /* 公司相关 api */
  getCompInfo: '/api/admin/company/info', // 获取公司信息
  editCompInfo: '/api/admin/company/edit-info', // 更新公司信息
  getCompIntro: '/api/admin/company/intro', // 获取公司介绍
  editCompIntro: '/api/admin/company/edit-intro', // 更新公司介绍
  /* 招班动态相关 api */
  getAdmiInfo: '/api/admin/admission/info', // 获取招班动态
  editAdmiInfo: '/api/admin/admission/edit-info', // 更新招班动态
  /* 教师相关 api */
  uploadTeacherAvatar: 'http://localhost/YiZhan/public/api/admin/teacher/upload-avatar', // 上传教师头像
  getImageLimit: '/api/admin/teacher/limit', // 获取对教师上传图片的大小和数量限制
  uploadTeacherWork: 'http://localhost/YiZhan/public/api/admin/teacher/upload-work', // 上传教师作品
  addTeacher: '/api/admin/teacher/add-teacher', // 添加教师
  teachList: '/api/admin/teacher/list', // 获取教师列表
  delTeacher: '/api/admin/teacher/del-teacher', // 删除教师
  getTeacher: '/api/admin/teacher/get', // 请求获取教师信息
  editTeacher: '/api/admin/teacher/edit', // 请求修改教师信息
  /* 学生相关 api */
  uploadStudentAvatar: 'http://localhost/YiZhan/public/api/admin/student/upload-avatar', // 上传学生头像
  uploadStudentWorks: 'http://localhost/YiZhan/public/api/admin/student/upload-work', // 上传学生作品集
  addStudent: '/api/admin/student/add-student', // 添加学生
  studentList: '/api/admin/student/list', // 获取学生列表
  getStudent: '/api/admin/student/get', // 请求获取学员信息
  editStudent: '/api/admin/student/edit', // 请求修改学员信息
  delStudent: '/api/admin/student/del-student', // 删除学员
  /* 我要保名相关 api */
  getSignList: '/api/admin/sign/list', // 获取保名学生列表
  delSign: '/api/admin/sign/del-sign', // 删除报名者
  /* 站点配置相关 api */
  getSiteHome: '/api/admin/site/get', // 获取站点首页图片等信息
  uploadHomePics: 'http://localhost/YiZhan/public/api/admin/site/upload-pics', // 上传首页轮播图
  setSiteHome: '/api/admin/site/set', // 设置站点首页图片等信息
  getConf: '/api/admin/site/conf', // 请求获取站点配置信息
  editConf: '/api/admin/site/edit-conf', // 请求修改站点配置信息
  /* 统计相关 api */
  siteStatistics: '/api/admin/site/statistics' // 请求统计数据
}
